### ISSUE TITLE
composer hatası

### ISSUE THREAD

**Issue by fuyasoft** [mustafa-m-ugur/trendyol-php-api#1]
Merhaba. composer i çalıştırdığım da 

In PackageDiscoveryTrait.php line 331:

  Could not find a version of package mustafa-m-ugur/trendyol-api-php matching your minimum-stability (stable). Requi
  re it with an explicit version constraint allowing its desired stability.

bu hatayı alıyorum yardımcı olur musunuz?

**Comment by mustafa-m-ugur** [comment]
Merhabai composer versiyon güncelleme yaparsanız çözülecektir.

composer selfupdate --2

**Comment by fuyasoft** [comment]
yaptım güncelledi fakat yine aynı hatayı vermeye devam ediyor.

**Comment by fuyasoft** [comment]
Could not find a version of package mustafa-m-ugur/trendyol-api-php matching your minimum-stability (stable). Requi
  re it with an explicit version constraint allowing its desired stability.


bu defa da yukarıdaki hatayı veriyor

**Comment by garsamba** [comment]
evet bendede aynı hatayı vermekte.

**Comment by mustafa-m-ugur** [comment]
composer.json dosyası içinden "minimum-stability": "stable" kaldırıp deneyebilirsiniz
